# fly.toml app configuration file generated for bio-backend on 2023-10-28T14:15:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bio-backend"
primary_region = "iad"

[env]
PORT = "4000"

[build]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
